### ISSUE TITLE
Index page throws error on load

### ISSUE THREAD

**Issue by bhupendrasinghnegi** [SolrNet/SolrNetSampleApps#3]
Hi Kindly help this might not be an issue but I am looking into this for a while now.
Every thing builds up perfectly but the index page throws the following error.

Error : "Compiler Error Message: CS1061: 'object' does not contain a definition for 'Search' and no extension method 'Search' accepting a first argument of type 'object' could be found (are you missing a using directive or an assembly reference?)"

https://github.com/SolrNet/SolrNetSampleApps/blob/master/SampleSolrApp/Views/Home/Index.aspx

Line 11:         <%= Html.TextBox("q", Model.Search.FreeSearch) %>

I have not changed anything

**Comment by mausch** [comment]
Sorry nobody ever replied to this. Anyway I've now rewritten this sample app, it's dockerised so things like this should never happen.
