### ISSUE TITLE
Application not run

### ISSUE THREAD

**Issue by YousefGhafouri** [SolrNet/SolrNetSampleApps#5]
Hi
I got an error after executing the code on VS 2022.
Please help me fix the error

![Screenshot 2022-06-05 154606](https://user-images.githubusercontent.com/52343597/172048014-fa49957b-5b94-4358-ae2c-25af8240e5c2.png)
.

**Comment by mausch** [comment]
Hi, check the logs for the Solr docker container.

**Comment by YousefGhafouri** [comment]
How do I view the log?

**Comment by mausch** [comment]
`docker ps -a` will show a container with a name like `SampleSolrApp-Solr-e6fffc6f-07be-4940-8abd-a3e3d869a18b` (last bit is random).
Then run `docker logs SampleSolrApp-Solr-e6fffc6f-07be-4940-8abd-a3e3d869a18b` to view the container logs.

**Comment by YousefGhafouri** [comment]
Thanks for the reply.
I think this error was because Docker was not installed.
But after installing Docker, I got this error. Do I have to make any settings in Docker?

![Screenshot 2022-06-07 123559](https://user-images.githubusercontent.com/52343597/172329152-fbe76ebd-df64-4753-93ac-b1d49c448a76.png)

**Comment by mausch** [comment]
Seems your docker instance is not pulling the image. Try running `docker pull solr:8.8.2`.

**Comment by YousefGhafouri** [comment]
Thanks
The problem was solved.
